{% set name = "gistim" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gistim-{{ version }}.tar.gz
  sha256: 35eaa9cd591837d4882c2cf28965615366219b15329e92fec3c712136f3efbc0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - black
    - fiona
    - geopandas
    - matplotlib-base
    - lmfit >=1.0
    - netcdf4
    - numba >=0.50
    - numpy
    - python >=3.8
    - rasterio
    - rioxarray
    - scipy >=1.5
    - shapely >=2.0
    - tqdm
    - timml
    - ttim
    - xarray >=0.15

test:
  imports:
    - gistim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/imod/qgis-tim
  summary: GIS utilities for TimML and TTim Analytic Element modeling
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://deltares.gitlab.io/imod/qgis-tim
  dev_url: https://gitlab.com/deltares/imod/qgis-tim

extra:
  recipe-maintainers:
    - Huite
    - visr
    - JoerivanEngelen
